/**
 * Market & Dispute capability descriptors.
 */
import type { Web3PluginConfig } from "../../config.js";
import type { CapabilityDescriptor } from "../types.js";
import { availability } from "./shared.js";

export function marketCapabilities(config: Web3PluginConfig): CapabilityDescriptor[] {
  const resourcesEnabled = config.resources.enabled;
  const advertiseEnabled = resourcesEnabled && config.resources.advertiseToMarket;
  const consumerEnabled = resourcesEnabled && config.resources.consumer.enabled;

  return [
    // ── Market ─────────────────────────────────────────
    {
      name: "web3.market.metrics.snapshot",
      summary: "Snapshot market metrics for monitoring dashboards.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      returns: "Market metrics snapshot payload.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.reconciliation.summary",
      summary: "Generate a dual-stack payment receipt + ledger reconciliation summary.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        properties: {
          orderId: { type: "string", description: "Order ID" },
          settlementId: { type: "string", description: "Settlement ID" },
          leaseId: { type: "string", description: "Optional lease ID for ledger summary" },
          chain: { type: "string", enum: ["ton", "evm"], description: "Payment chain hint" },
          network: { type: "string", description: "Chain network name" },
          includeLedger: { type: "boolean", description: "Include ledger summary" },
          includeDisputes: { type: "boolean", description: "Include dispute summary" },
        },
      },
      returns: "Reconciliation summary payload with payment receipt and ledger/dispute overview.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.reputation.summary",
      summary: "Summarize provider reputation signals and anti-cheat indicators.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        properties: {
          providerActorId: {
            type: "string",
            description: "Filter by provider actor ID",
            pattern: "^0x[a-fA-F0-9]{40}$",
          },
          resourceId: { type: "string", description: "Optional resource ID" },
          since: { type: "string", description: "ISO timestamp (optional)" },
          until: { type: "string", description: "ISO timestamp (optional)" },
          limit: {
            type: "number",
            description: "Max leases to consider",
            minimum: 1,
            maximum: 1000,
          },
        },
      },
      returns: "Reputation summary with score, signals, lease/dispute counts, and ledger totals.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.tokenEconomy.summary",
      summary: "Read the current token economy state and supply totals.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      returns: "Token economy policy, status, and supply totals.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.tokenEconomy.configure",
      summary: "Configure token economy policy and activation status.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        required: ["policy"],
        properties: {
          status: { type: "string", enum: ["token_draft", "token_active", "token_paused"] },
          policy: {
            type: "object",
            required: ["symbol"],
            properties: {
              symbol: { type: "string", description: "Token symbol" },
              name: { type: "string", description: "Token display name" },
              decimals: { type: "number", minimum: 0, maximum: 30 },
              chain: { type: "string", description: "Chain identifier" },
              tokenAddress: {
                type: "string",
                pattern: "^0x[a-fA-F0-9]{40}$",
                description: "Optional EVM token address",
              },
              emission: {
                type: "object",
                properties: {
                  rate: { type: "string", pattern: "^[0-9]+$" },
                  period: { type: "string", enum: ["day", "week", "month"] },
                  cap: { type: "string", pattern: "^[0-9]+$" },
                },
              },
              burn: {
                type: "object",
                properties: { burnRateBps: { type: "number", minimum: 0, maximum: 10000 } },
              },
              governance: {
                type: "object",
                properties: {
                  quorumBps: { type: "number", minimum: 0, maximum: 10000 },
                  votingPeriodDays: { type: "number", minimum: 1, maximum: 365 },
                  proposalThreshold: { type: "string", pattern: "^[0-9]+$" },
                },
              },
            },
          },
        },
      },
      returns: "Updated token economy state.",
      risk: { level: "medium" },
    },
    {
      name: "web3.market.tokenEconomy.mint",
      summary: "Mint tokens into circulation (authority only).",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        required: ["amount"],
        properties: {
          amount: { type: "string", pattern: "^[0-9]+$" },
          reason: { type: "string" },
        },
      },
      returns: "Updated token economy state.",
      risk: { level: "medium" },
    },
    {
      name: "web3.market.tokenEconomy.burn",
      summary: "Burn tokens from circulation (authority only).",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        required: ["amount"],
        properties: {
          amount: { type: "string", pattern: "^[0-9]+$" },
          reason: { type: "string" },
        },
      },
      returns: "Updated token economy state.",
      risk: { level: "medium" },
    },
    {
      name: "web3.market.tokenEconomy.governance.update",
      summary: "Update governance thresholds for the token economy.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        required: ["governance"],
        properties: {
          governance: {
            type: "object",
            properties: {
              quorumBps: { type: "number", minimum: 0, maximum: 10000 },
              votingPeriodDays: { type: "number", minimum: 1, maximum: 365 },
              proposalThreshold: { type: "string", pattern: "^[0-9]+$" },
            },
          },
          reason: { type: "string" },
        },
      },
      returns: "Updated token economy state.",
      risk: { level: "medium" },
    },
    // ── Bridge ──────────────────────────────────────────
    {
      name: "web3.market.bridge.routes",
      summary: "List available cross-chain bridge routes and assets.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        properties: {
          fromChain: { type: "string", enum: ["ton", "evm"] },
          toChain: { type: "string", enum: ["ton", "evm"] },
          assetSymbol: { type: "string", description: "Asset symbol filter" },
        },
      },
      returns: "Bridge route list with supported assets and fees.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.bridge.request",
      summary: "Request a cross-chain bridge transfer tied to an order or settlement.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        required: ["fromChain", "toChain", "assetSymbol", "amount"],
        properties: {
          orderId: { type: "string" },
          settlementId: { type: "string" },
          fromChain: { type: "string", enum: ["ton", "evm"] },
          toChain: { type: "string", enum: ["ton", "evm"] },
          assetSymbol: { type: "string" },
          amount: { type: "string", pattern: "^[0-9]+$" },
        },
      },
      returns: "Bridge transfer request record.",
      risk: { level: "medium" },
    },
    {
      name: "web3.market.bridge.update",
      summary: "Update bridge transfer status and receipt metadata.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        required: ["bridgeId"],
        properties: {
          bridgeId: { type: "string" },
          status: {
            type: "string",
            enum: ["bridge_requested", "bridge_in_flight", "bridge_completed", "bridge_failed"],
          },
          txHash: { type: "string" },
          failureReason: { type: "string" },
        },
      },
      returns: "Updated bridge transfer record.",
      risk: { level: "medium" },
    },
    {
      name: "web3.market.bridge.status",
      summary: "Get bridge transfer status by ID or settlement link.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        properties: {
          bridgeId: { type: "string" },
          orderId: { type: "string" },
          settlementId: { type: "string" },
        },
      },
      returns: "Bridge transfer record.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.bridge.list",
      summary: "List bridge transfer records with optional filters.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      paramsSchema: {
        type: "object",
        properties: {
          orderId: { type: "string" },
          settlementId: { type: "string" },
          fromChain: { type: "string", enum: ["ton", "evm"] },
          toChain: { type: "string", enum: ["ton", "evm"] },
          assetSymbol: { type: "string" },
          status: {
            type: "string",
            enum: ["bridge_requested", "bridge_in_flight", "bridge_completed", "bridge_failed"],
          },
          limit: { type: "number", minimum: 1, maximum: 1000 },
        },
      },
      returns: "Bridge transfer list.",
      risk: { level: "low" },
    },
    // ── Market status & CRUD ───────────────────────────
    {
      name: "web3.market.status.summary",
      summary: "Summarize market-core status totals and counts.",
      kind: "gateway",
      group: "market",
      availability: availability(true),
      returns: "Market status totals and breakdowns.",
      risk: { level: "low" },
    },
    {
      name: "web3.market.resource.publish",
      summary: "Market entrypoint for resource publish (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(advertiseEnabled, "resources advertise disabled"),
      paramsSchema: {
        type: "object",
        required: ["actorId", "resource"],
        properties: {
          actorId: {
            type: "string",
            description: "Provider actor identifier (required)",
            pattern: "^0x[a-fA-F0-9]{40}$",
            example: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
          },
          resource: {
            type: "object",
            description: "Market resource payload",
            required: ["kind", "label", "price", "offer"],
            properties: {
              resourceId: {
                type: "string",
                description: "Optional resourceId override (advanced)",
              },
              kind: {
                type: "string",
                description: "Resource kind",
                enum: ["model", "search", "storage"],
                example: "storage",
              },
              label: {
                type: "string",
                description: "Short display label",
                maxLength: 80,
                example: "Fast IPFS Storage",
              },
              description: {
                type: "string",
                description: "Optional description",
                maxLength: 400,
                example: "100TB IPFS-compatible storage",
              },
              tags: {
                type: "array",
                description: "Optional tags",
                items: { type: "string" },
                maxItems: 12,
                example: ["ipfs", "storage"],
              },
              price: {
                type: "object",
                description: "Pricing definition",
                required: ["unit", "amount", "currency"],
                properties: {
                  unit: {
                    type: "string",
                    description: "Billing unit (must match resource kind)",
                    enum: ["token", "call", "query", "gb_day", "put", "get"],
                    example: "gb_day",
                  },
                  amount: {
                    type: "string",
                    description: "Price per unit (decimal string)",
                    pattern: "^[0-9]+(\\.[0-9]+)?$",
                    example: "0.001",
                  },
                  currency: {
                    type: "string",
                    description: "Payment token symbol",
                    example: "USDT",
                  },
                  tokenAddress: {
                    type: "string",
                    description: "Optional ERC-20 token address",
                    pattern: "^0x[a-fA-F0-9]{40}$",
                  },
                },
              },
              policy: {
                type: "object",
                description: "Optional usage policy constraints",
                properties: {
                  maxConcurrent: { type: "number", minimum: 1, maximum: 1000 },
                  maxTokens: { type: "number", minimum: 1, maximum: 200000 },
                  maxBytes: { type: "number", minimum: 1, maximum: 1073741824 },
                  allowTools: { type: "boolean" },
                  allowMime: { type: "array", items: { type: "string" }, maxItems: 64 },
                },
              },
              offer: {
                type: "object",
                description: "Offer metadata (must align with price.currency)",
                required: ["assetId", "assetType", "currency", "usageScope", "deliveryType"],
                properties: {
                  assetId: { type: "string", description: "Asset identifier" },
                  assetType: {
                    type: "string",
                    description: "Asset type",
                    enum: ["data", "api", "service"],
                  },
                  currency: { type: "string", description: "Must match price.currency" },
                  usageScope: {
                    type: "object",
                    description: "Usage scope",
                    required: ["purpose"],
                    properties: { purpose: { type: "string" } },
                  },
                  deliveryType: {
                    type: "string",
                    description: "Delivery type",
                    enum: ["download", "api", "service"],
                  },
                  assetMeta: { type: "object", description: "Optional asset metadata" },
                },
              },
            },
          },
        },
      },
      returns: "Published resource record with generated resourceId.",
      aliases: ["web3.resources.publish"],
      examples: [
        {
          summary: "Publish a storage resource",
          params: {
            actorId: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
            resource: {
              kind: "storage",
              label: "Fast IPFS Storage",
              description: "100TB IPFS-compatible storage",
              tags: ["ipfs", "high-speed"],
              price: { unit: "gb_day", amount: "0.001", currency: "USDT" },
              offer: {
                assetId: "web3:storage:ipfs-fast",
                assetType: "api",
                currency: "USDT",
                usageScope: { purpose: "storage" },
                deliveryType: "api",
              },
            },
          },
        },
      ],
    },
    {
      name: "web3.market.resource.unpublish",
      summary: "Market entrypoint for resource unpublish (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(advertiseEnabled, "resources advertise disabled"),
      paramsSchema: {
        type: "object",
        required: ["actorId", "resourceId"],
        properties: {
          actorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          resourceId: { type: "string" },
        },
      },
      returns: "Unpublish result.",
      aliases: ["web3.resources.unpublish"],
    },
    {
      name: "web3.market.resource.get",
      summary: "Market entrypoint for resource lookup (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["resourceId"],
        properties: { resourceId: { type: "string" } },
      },
      returns: "Resource record.",
    },
    {
      name: "web3.market.resource.list",
      summary: "Market entrypoint for resource listing (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          kind: {
            type: "string",
            description: "Filter by resource kind (optional)",
            enum: ["model", "search", "storage"],
          },
          providerActorId: {
            type: "string",
            description: "Filter by provider actor ID (optional)",
            pattern: "^0x[a-fA-F0-9]{40}$",
          },
          status: {
            type: "string",
            description: "Filter by resource status (optional)",
            enum: ["resource_draft", "resource_published", "resource_unpublished"],
          },
          tag: { type: "string", description: "Filter by tag (optional)" },
          limit: { type: "number", minimum: 1, maximum: 200 },
        },
      },
      returns: "Resource list response.",
      aliases: ["web3.resources.list"],
      examples: [
        { summary: "List first 10 storage resources", params: { limit: 10, kind: "storage" } },
        { summary: "List IPFS-tagged resources", params: { tag: "ipfs", limit: 20 } },
      ],
    },
    // ── Lease ───────────────────────────────────────────
    {
      name: "web3.market.lease.issue",
      summary: "Market entrypoint for lease issuance (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(consumerEnabled, "resources consumer disabled"),
      paramsSchema: {
        type: "object",
        required: ["actorId", "resourceId", "consumerActorId", "ttlMs"],
        properties: {
          actorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          resourceId: { type: "string", description: "Target resource ID" },
          consumerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          ttlMs: {
            type: "number",
            description: "Lease duration in milliseconds",
            minimum: 10000,
            maximum: 604800000,
          },
          maxCost: {
            type: "string",
            description: "Optional max cost (decimal string)",
            pattern: "^[0-9]+(\\.[0-9]+)?$",
          },
        },
      },
      returns:
        "Lease response with leaseId/orderId/consentId/deliveryId/expiresAt/stored (no token or endpoint).",
      aliases: ["web3.resources.lease"],
      risk: { level: "high", notes: ["Access token stored internally; never returned"] },
      pricing: { requiresPreLock: true },
      examples: [
        {
          summary: "Issue lease for storage resource",
          params: {
            actorId: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199",
            resourceId: "res_abc123",
            consumerActorId: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199",
            ttlMs: 86400000,
          },
        },
      ],
    },
    {
      name: "web3.market.lease.revoke",
      summary: "Market entrypoint for lease revocation (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["actorId", "leaseId"],
        properties: {
          actorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          leaseId: { type: "string" },
          reason: { type: "string" },
        },
      },
      returns: "Revocation result.",
      aliases: ["web3.resources.revokeLease"],
    },
    {
      name: "web3.market.lease.get",
      summary: "Market entrypoint for lease lookup (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["leaseId"],
        properties: {
          leaseId: { type: "string" },
          actorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
        },
      },
      returns: "Lease record.",
    },
    {
      name: "web3.market.lease.list",
      summary: "Market entrypoint for lease listing (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          providerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          consumerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          resourceId: { type: "string" },
          status: { type: "string", enum: ["lease_active", "lease_revoked", "lease_expired"] },
          limit: { type: "number", minimum: 1, maximum: 200 },
        },
      },
      returns: "Lease list response.",
    },
    {
      name: "web3.market.lease.expireSweep",
      summary: "Expire stale leases (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          actorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          now: { type: "string", description: "ISO timestamp (optional)" },
          limit: { type: "number", minimum: 1, maximum: 1000 },
          dryRun: { type: "boolean" },
        },
      },
      returns: "Expiration sweep summary.",
    },
    // ── Ledger ──────────────────────────────────────────
    {
      name: "web3.market.ledger.list",
      summary: "List ledger entries (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          leaseId: { type: "string" },
          resourceId: { type: "string" },
          providerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          consumerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          since: { type: "string", description: "ISO timestamp (optional)" },
          until: { type: "string", description: "ISO timestamp (optional)" },
          limit: { type: "number", minimum: 1, maximum: 200 },
        },
      },
      returns: "Ledger entries list.",
      examples: [
        { summary: "List last 50 ledger entries", params: { limit: 50 } },
        { summary: "List entries for a specific lease", params: { leaseId: "lease_xyz789" } },
      ],
    },
    {
      name: "web3.market.ledger.summary",
      summary: "Summarize ledger totals (proxy to market-core).",
      kind: "gateway",
      group: "market",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          resourceId: { type: "string" },
          leaseId: { type: "string" },
          providerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          consumerActorId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          since: { type: "string" },
          until: { type: "string" },
        },
      },
      returns: "Ledger summary with total charges, refunds, and net balance.",
      examples: [
        { summary: "Get ledger summary for a lease", params: { leaseId: "lease_xyz789" } },
      ],
    },
    // ── Dispute ─────────────────────────────────────────
    {
      name: "web3.dispute.open",
      summary: "Open a dispute for an order or lease.",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["orderId", "reason", "resourceId", "consumerId", "providerId"],
        properties: {
          orderId: { type: "string", description: "Order or lease identifier" },
          reason: {
            type: "string",
            description: "Dispute reason (10-500 chars)",
            minLength: 10,
            maxLength: 500,
          },
          resourceId: { type: "string", description: "Resource ID" },
          consumerId: {
            type: "string",
            description: "Consumer actor ID",
            pattern: "^0x[a-fA-F0-9]{40}$",
          },
          providerId: {
            type: "string",
            description: "Provider actor ID",
            pattern: "^0x[a-fA-F0-9]{40}$",
          },
        },
      },
      returns: "Dispute opened status with expiry information.",
      risk: { level: "medium", notes: ["Creates dispute record"] },
    },
    {
      name: "web3.dispute.submitEvidence",
      summary: "Submit dispute evidence.",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId", "submittedBy", "description"],
        properties: {
          disputeId: { type: "string", description: "Dispute ID" },
          submittedBy: {
            type: "string",
            description: "Submitting party actor ID",
            pattern: "^0x[a-fA-F0-9]{40}$",
          },
          type: {
            type: "string",
            description: "Evidence type",
            enum: ["usage_log", "screenshot", "api_response", "other"],
          },
          description: { type: "string", description: "Evidence summary" },
          data: { type: "object", description: "Optional evidence payload (limited size)" },
        },
      },
      returns: "Evidence submission status with content hash.",
      risk: { level: "medium" },
    },
    {
      name: "web3.dispute.resolve",
      summary: "Resolve a dispute with a ruling.",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId", "ruling", "reason"],
        properties: {
          disputeId: { type: "string", description: "Dispute ID" },
          ruling: {
            type: "string",
            description: "Resolution ruling",
            enum: ["provider_wins", "consumer_wins", "split", "timeout"],
          },
          reason: { type: "string", description: "Resolution reason" },
          refundAmount: {
            type: "string",
            description: "Optional refund amount (decimal string)",
            pattern: "^[0-9]+(\\.[0-9]+)?$",
          },
          resolvedBy: { type: "string", description: "Resolver actor ID or system" },
        },
      },
      returns: "Resolution result with ruling details.",
      risk: { level: "medium" },
    },
    {
      name: "web3.dispute.reject",
      summary: "Reject a dispute without ruling.",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId"],
        properties: {
          disputeId: { type: "string", description: "Dispute ID" },
          reason: { type: "string", description: "Optional rejection reason" },
        },
      },
      returns: "Rejection result.",
      risk: { level: "medium" },
    },
    {
      name: "web3.dispute.get",
      summary: "Get a dispute record.",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId"],
        properties: { disputeId: { type: "string", description: "Dispute ID" } },
      },
      returns: "Dispute record.",
      risk: { level: "low" },
    },
    {
      name: "web3.dispute.list",
      summary: "List dispute records.",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          orderId: { type: "string", description: "Filter by order/lease ID" },
          status: {
            type: "string",
            description: "Filter by dispute status",
            enum: ["open", "evidence_submitted", "resolved", "rejected", "expired"],
          },
          limit: { type: "number", description: "Max records to return", minimum: 1, maximum: 100 },
        },
      },
      returns: "Dispute list.",
      risk: { level: "low" },
    },
    // ── Dispute (market namespace aliases) ──────────────
    {
      name: "web3.market.dispute.open",
      summary: "Open a dispute for an order or lease (market namespace).",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["orderId", "reason", "resourceId", "consumerId", "providerId"],
        properties: {
          orderId: { type: "string", description: "Order or lease identifier" },
          reason: {
            type: "string",
            description: "Dispute reason (10-500 chars)",
            minLength: 10,
            maxLength: 500,
          },
          resourceId: { type: "string", description: "Resource ID" },
          consumerId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          providerId: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
        },
      },
      returns: "Dispute opened status with expiry information.",
      aliases: ["web3.dispute.open"],
      risk: { level: "medium" },
    },
    {
      name: "web3.market.dispute.submitEvidence",
      summary: "Submit dispute evidence (market namespace).",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId", "submittedBy", "description"],
        properties: {
          disputeId: { type: "string", description: "Dispute ID" },
          submittedBy: { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" },
          type: { type: "string", enum: ["usage_log", "screenshot", "api_response", "other"] },
          description: { type: "string", description: "Evidence summary" },
          data: { type: "object", description: "Optional evidence payload" },
        },
      },
      returns: "Evidence submission result.",
      aliases: ["web3.dispute.submitEvidence"],
      risk: { level: "medium" },
    },
    {
      name: "web3.market.dispute.resolve",
      summary: "Resolve a dispute with a ruling (market namespace).",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId", "ruling", "reason"],
        properties: {
          disputeId: { type: "string", description: "Dispute ID" },
          ruling: { type: "string", enum: ["provider_wins", "consumer_wins", "split", "timeout"] },
          reason: { type: "string", description: "Resolution reason" },
          refundAmount: { type: "string", pattern: "^[0-9]+(\\.[0-9]+)?$" },
          resolvedBy: { type: "string", description: "Resolver actor ID or system" },
        },
      },
      returns: "Resolution result with ruling details.",
      aliases: ["web3.dispute.resolve"],
      risk: { level: "medium" },
    },
    {
      name: "web3.market.dispute.reject",
      summary: "Reject a dispute without ruling (market namespace).",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId"],
        properties: {
          disputeId: { type: "string", description: "Dispute ID" },
          reason: { type: "string", description: "Optional rejection reason" },
        },
      },
      returns: "Rejection result.",
      aliases: ["web3.dispute.reject"],
      risk: { level: "medium" },
    },
    {
      name: "web3.market.dispute.get",
      summary: "Get a dispute record (market namespace).",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        required: ["disputeId"],
        properties: { disputeId: { type: "string", description: "Dispute ID" } },
      },
      returns: "Dispute record.",
      aliases: ["web3.dispute.get"],
      risk: { level: "low" },
    },
    {
      name: "web3.market.dispute.list",
      summary: "List dispute records (market namespace).",
      kind: "gateway",
      group: "dispute",
      availability: availability(resourcesEnabled, "resources disabled"),
      paramsSchema: {
        type: "object",
        properties: {
          orderId: { type: "string", description: "Filter by order/lease ID" },
          status: {
            type: "string",
            description: "Filter by dispute status",
            enum: ["open", "evidence_submitted", "resolved", "rejected", "expired"],
          },
          limit: { type: "number", description: "Max records to return", minimum: 1, maximum: 100 },
        },
      },
      returns: "Dispute list.",
      aliases: ["web3.dispute.list"],
      risk: { level: "low" },
    },
  ];
}
